### ISSUE TITLE
No Apex Drivers Loaded on Unraid

### ISSUE THREAD

**Issue by mitchross** [ich777/unraid-coral-driver#2]
Using  PCI m2 Coral , I dont see the apex drivers in unraid 

root@Tower:~# ls -l /dev/apex_*
/bin/ls: cannot access '/dev/apex_*': No such file or directory

I do see the PCI device however
03:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
04:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU

Im trying to pass the PCI coral over to a docker instance.

im using the coral drivers plugin. Unraid 6.10 rc

Interesting part is that im using a new dual edge adapter card that exposes both tpu cores to the system. In a VM I can get everything to work and can use Frigate with dual TPUs even with docker in the VM... But on the Frigate docker instance in Unraid, it cant see the dual tpu pci card?

some content -> https://github.com/blakeblackshear/frigate/issues/1428

**Comment by ich777** [comment]
On what unRAID version are you?
Can you give me the output from `lsmod`?

**Comment by mitchross** [comment]
@ich777 

```
root@Tower:~# lsmod
Module                  Size  Used by
nct6775                65536  0
hwmon_vid              16384  1 nct6775
apex                   16384  0
gasket                 94208  1 apex
ip6table_filter        16384  1
ip6_tables             28672  1 ip6table_filter
iptable_filter         16384  1
ip_tables              28672  1 iptable_filter
x_tables               45056  4 ip6table_filter,iptable_filter,ip6_tables,ip_tables
bonding               131072  0
edac_mce_amd           32768  0
kvm_amd               122880  0
kvm                   864256  1 kvm_amd
crct10dif_pclmul       16384  1
crc32_pclmul           16384  0
crc32c_intel           24576  0
ghash_clmulni_intel    16384  0
aesni_intel           380928  0
wmi_bmof               16384  0
crypto_simd            16384  1 aesni_intel
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
input_leds             16384  0
rapl                   16384  0
r8169                  77824  0
wmi                    28672  1 wmi_bmof
led_class              16384  1 input_leds
i2c_piix4              24576  0
i2c_core               86016  1 i2c_piix4
ahci                   40960  0
realtek                24576  1
k10temp                16384  0
ccp                    81920  1 kvm_amd
libahci                40960  1 ahci
button                 16384  0
root@Tower:~# 

```

```
root@Tower:~# uname -a
Linux Tower 5.13.8-Unraid #1 SMP Wed Aug 4 09:39:46 PDT 2021 x86_64 AMD Ryzen 5 1600 Six-Core Processor AuthenticAMD GNU/Linux
root@Tower:~# 

```

Unraid 6.10rc1

**Comment by mitchross** [comment]
moving convo to https://forums.unraid.net/topic/92865-support-ich777-nvidiadvbzfsiscsimft-kernel-helperbuilder-docker/page/38/?tab=comments#comment-1023476
