### ISSUE TITLE
Multiple coral temps are not read separately

### ISSUE THREAD

**Issue by NickM-27** [ich777/unraid-coral-driver#4]
I have two PCIe corals. In the unraid plugins page they both show as the same temperature

![Screen Shot 2022-07-21 at 10 13 38 AM](https://user-images.githubusercontent.com/14866235/180262836-6672d3e7-bf1d-471c-b17b-ddc64495f530.png)

However checking the temps manually shows that they are different

![Screen Shot 2022-07-21 at 10 14 11 AM](https://user-images.githubusercontent.com/14866235/180262955-bd1fbd0e-1181-4470-bc19-2b765235a5ac.png)

**Comment by ich777** [comment]
@NickM-27 thank you for the report, I will look into that tomorrow and report back.
I have only one Coral TPU and couldn't test this until now.

**Comment by ich777** [comment]
@NickM-27 are you still around, I think I've found the issue.

**Comment by NickM-27** [comment]
Yep, ready to try

**Comment by ich777** [comment]
I think you are familiar with the command line?
Please edit the file: `/usr/local/emhttp/plugins/coral-driver/coraltpu.page` and go to line 39 and change it to:
`    $temp = shell_exec("/usr/local/emhttp/plugins/coral-driver/include/exec.sh get_temp ".escapeshellarg($device)."");`

**Comment by NickM-27** [comment]
Oh yeah that did it!

<img width="1213" alt="Screen Shot 2022-07-21 at 12 06 08 PM" src="https://user-images.githubusercontent.com/14866235/180283402-fbf90950-995b-4691-9989-f702dfbda965.png">

**Comment by ich777** [comment]
Nice, thank you for trying and the inconvenience... Got lot's of stuff to do in real life currently and on the side my Unraid things and joining them together is currently really hard.

Will push an update shortly.
Thank you and sorry again.

**Comment by NickM-27** [comment]
Oh hey nothing to be sorry about! Glad that I was able to help get this sorted out 👍

**Comment by ich777** [comment]
Updated is pushed [7a78b33](https://github.com/ich777/unraid-coral-driver/commit/7a78b33242ab8ce0dda35c01427740e0558de91b)
