### ISSUE TITLE
Add a coral temperature graph to Unraid Dashboard?

### ISSUE THREAD

**Issue by NickM-27** [ich777/unraid-coral-driver#5]
This is something I would be interested in contributing (or at least attempting to!), but wanted to know if it is possible and if it would be accepted into this package (since it's a driver and not necessarily offering that functionality).

Thanks!

**Comment by ich777** [comment]
@NickM-27 sure thing PRs are accepted if the plugin benefits from it... :)

You should find everything, or at least the web page, in the source folder and or on your Unraid server in `/usr/local/emhttp/plugins/coral-driver/`

**Comment by TRusselo** [comment]
i would LOVE to see graphs added to the unraid dashboard!
i came here to suggest this. and its the ONLY thing in the issue tracker!
![image](https://user-images.githubusercontent.com/1154815/189248469-bd4ce18d-0e96-4c03-a0ab-7ebb0e1aa771.png)

**Comment by ich777** [comment]
@TRusselo as said above I accept Pull Requests, if you have time to code this up I will test it and also merge it into the plugin, don't know if @NickM-27 already started with this.

**Comment by NickM-27** [comment]
I haven't had a chance to start yet but I'd like to if someone else doesn't start first. Quite busy with other projects at the moment.

**Comment by ich777** [comment]
@NickM-27 same over here, too much work and too less free time to start creating a temperature graph for the Dashboard.

**Comment by ich777** [comment]
@NickM-27 & @TRusselo please update the plugin, both requests are now implemented.

**Comment by NickM-27** [comment]
that's awesome!

**Comment by ich777** [comment]
Completely forgot to take screenshots *facepalm*, but the plugin got a complete overhaul including the dashboard page. :)

**Comment by TRusselo** [comment]
updated... but dont see any difference...?

**Comment by ich777** [comment]
A bit more information would be nice.
Have you tried force reloading the page?
CTRL + F5
Also clear the cookies, on what version are you now?

**Comment by ich777** [comment]
@TRusselo here it is what it looks like on my system:

Dashboard:
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/6edd8735-3c0a-49d3-80a5-ee9a1de350bd)

Plugin Page:
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/996e30df-9f41-4837-9a3a-e5b687d11429)

With Dual EDGE TPU:
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/480b4e9c-1730-40a7-888e-979d7d37bb43)
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/bcd60578-35b0-461f-b23c-067a703933f9)

With many TPUs:
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/f245827a-e9f1-45f2-93a2-0984fef942a1)
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/f79b4416-850d-4163-8c27-5eb1c4df56dd)

**Comment by TRusselo** [comment]
> A bit more information would be nice. Have you tried force reloading the page? CTRL + F5 Also clear the cookies, on what version are you now?

6.11.5
cleared cache no-go

I was planning on updating anyway. ill try that.

**Comment by ich777** [comment]
> 6.11.5

Why are you on such an old version? Please upgrade...
The new Dashbaord page is only visible on 6.12.0+
