### ISSUE TITLE
failing to install on Unraid v6.12.3

### ISSUE THREAD

**Issue by arcoast** [ich777/unraid-coral-driver#7]
```bash
plugin: installing: coral-driver.plg
Executing hook script: pre_plugin_checks
plugin: downloading: coral-driver.plg ... done

plugin: downloading: coral-driver-2022.11.14.txz ... done


+==============================================================================
| Skipping package coral-driver-2022.11.14 (already installed)
+==============================================================================


---------------Downloading Coral Accelerator Module Drivers!-----------------
---------This could take some time, please don't close this window!----------

--------------Can't download Coral Accelerator Module Drivers----------------
plugin: run failed: '/bin/bash' returned 1
Executing hook script: post_plugin_checks
```

Was working fine on the previous version of Unraid then got an error message about the Coral plugin so removed it and rebooted to upgrade Unraid and then tried reinstalling it.

The plugin isn't showing up on my Unraid GUI and the exit code of 1 on the bash script was the same when I first tried installing it after a clean boot with the plugin removed.

**Comment by ich777** [comment]
Please post your full Diagnostics but before do the following:

1. Remove the plugin
2. Reboot
3. Install the plugin again

If that doesn't work pull the Diagnostics and post them here.

EDIT: I've now also tried it and it is working just fine:
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/b28028e1-cbad-4083-9fa0-c021a27c8ec9)
![grafik](https://github.com/ich777/unraid-coral-driver/assets/28066518/346e8377-53de-4627-919b-769f07c14221)

**Comment by arcoast** [comment]
Yeah, something weird is going on.  This is all that's in the syslogs

```
Jul 19 13:04:44 lantallack root: plugin: running: anonymous
Jul 19 13:04:44 lantallack root: plugin: creating: /boot/config/plugins/coral-driver/coral-driver-2022.11.14.txz - downloading from URL https://github.com/ich777/unraid-coral-driver/raw/master/packages/coral-driver-2022.11.14.txz
Jul 19 13:04:45 lantallack root: plugin: checking: /boot/config/plugins/coral-driver/coral-driver-2022.11.14.txz - MD5
Jul 19 13:04:45 lantallack root: plugin: running: upgradepkg --install-new /boot/config/plugins/coral-driver/coral-driver-2022.11.14.txz
Jul 19 13:04:45 lantallack root: plugin: creating: /usr/local/emhttp/plugins/coral-driver/README.md - from INLINE content
Jul 19 13:04:45 lantallack root: plugin: running: anonymous
```

I can curl or wget that link from y server and works fine.  Which bit of the diagnostics is the relevant bit?

**Comment by arcoast** [comment]
Placing that package manually doesn't help me either
```

Install Plugin

plugin: installing: coral-driver.plg
Executing hook script: pre_plugin_checks
plugin: downloading: coral-driver.plg ... done

Executing hook script: pre_plugin_checks

+==============================================================================
| Skipping package coral-driver-2022.11.14 (already installed)
+==============================================================================


---------------Downloading Coral Accelerator Module Drivers!-----------------
---------This could take some time, please don't close this window!----------

--------------Can't download Coral Accelerator Module Drivers----------------
plugin: run failed: '/bin/bash' returned 1
Executing hook script: post_plugin_checks
```

**Comment by ich777** [comment]
You still haven't posted your Diagnostics from unRAID.

What network gear are you using? Do you use any AdBlocking on your network, make sure that you don't block `api.github.com`
Please note that this package that you see listed there is not the actual plugin package that makes all work.
I use GitHub API calls to determine which is the correct package for your unRAID version and then the plugin downloads it.
Have you yet rebooted or did the steps what I've told you?

**Comment by arcoast** [comment]
That was the answer!  `api.github.com`

Found I was hitting the rate limit due to a bug in pialert spamming the github api, which then blocked my ip address.  Thanks for the help.
